name: Build and Push

on:
  push:
    tags:
      - v*
    branches:
      - develop
jobs:
  build-and-push:

    runs-on: ubuntu-18.04
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-push
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO_NAME }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo ::set-output name=image-tag::${IMAGE_TAG}

    - name: Checkout manifest file
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.MANIFEST_REPO }}
        token: ${{ secrets.AUTOMATION_GITHUB_TOKEN }}
        path: ./

    - name: Update manifest file
      env: 
        SED_ECR_REPO_URI: ${{ secrets.SED_ECR_REPO_URL }}
        IMAGE_TAG:  ${{ steps.build-push.outputs.image-tag }}
      run: |
        echo $IMAGE_TAG
        sed -i "s/image: .*:.*/image: "$SED_ECR_REPO_URI":$IMAGE_TAG/;" service.yaml

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.AUTOMATION_GITHUB_TOKEN }}
        commit-message: "release: image version upate"
        branch: auto/image-version-update
        title: "release: image version upate"
        body: This PR updates container image to the latest version